import { t } from '@lingui/macro'

export const COUNTRIES = {
  'AF': t('Subscribe.contries.Afghanistan')`Afghanistan`,
  'AX': t('Subscribe.contries.AlandIslands')`Åland Islands`,
  'AL': t('Subscribe.contries.Albania')`Albania`,
  'DZ': t('Subscribe.contries.Algeria')`Algeria`,
  'AS': t('Subscribe.contries.AmericanSamoa')`American Samoa`,
  'AD': t('Subscribe.contries.AndorrA')`AndorrA`,
  'AO': t('Subscribe.contries.Angola')`Angola`,
  'AI': t('Subscribe.contries.Anguilla')`Anguilla`,
  'AQ': t('Subscribe.contries.Antarctica')`Antarctica`,
  'AG': t('Subscribe.contries.AntiguaAndBarbuda')`Antigua and Barbuda`,
  'AR': t('Subscribe.contries.Argentina')`Argentina`,
  'AM': t('Subscribe.contries.Armenia')`Armenia`,
  'AW': t('Subscribe.contries.Aruba')`Aruba`,
  'AU': t('Subscribe.contries.Australia')`Australia`,
  'AT': t('Subscribe.contries.Austria')`Austria`,
  'AZ': t('Subscribe.contries.Azerbaijan')`Azerbaijan`,
  'BS': t('Subscribe.contries.Bahamas')`Bahamas`,
  'BH': t('Subscribe.contries.Bahrain')`Bahrain`,
  'BD': t('Subscribe.contries.Bangladesh')`Bangladesh`,
  'BB': t('Subscribe.contries.Barbados')`Barbados`,
  'BY': t('Subscribe.contries.Belarus')`Belarus`,
  'BE': t('Subscribe.contries.Belgium')`Belgium`,
  'BZ': t('Subscribe.contries.Belize')`Belize`,
  'BJ': t('Subscribe.contries.Benin')`Benin`,
  'BM': t('Subscribe.contries.Bermuda')`Bermuda`,
  'BT': t('Subscribe.contries.Bhutan')`Bhutan`,
  'BO': t('Subscribe.contries.Bolivia')`Bolivia`,
  'BA': t('Subscribe.contries.BosniaAndHerzegovina')`Bosnia and Herzegovina`,
  'BW': t('Subscribe.contries.Botswana')`Botswana`,
  'BV': t('Subscribe.contries.BouvetIsland')`Bouvet Island`,
  'BR': t('Subscribe.contries.Brazil')`Brazil`,
  'IO': t('Subscribe.contries.BritishIndianOceanTerritory')`British Indian Ocean Territory`,
  'BN': t('Subscribe.contries.BruneiDarussalam')`Brunei Darussalam`,
  'BG': t('Subscribe.contries.Bulgaria')`Bulgaria`,
  'BF': t('Subscribe.contries.BurkinaFaso')`Burkina Faso`,
  'BI': t('Subscribe.contries.Burundi')`Burundi`,
  'KH': t('Subscribe.contries.Cambodia')`Cambodia`,
  'CM': t('Subscribe.contries.Cameroon')`Cameroon`,
  'CA': t('Subscribe.contries.Canada')`Canada`,
  'CV': t('Subscribe.contries.CapeVerde')`Cape Verde`,
  'KY': t('Subscribe.contries.CaymanIslands')`Cayman Islands`,
  'CF': t('Subscribe.contries.CentralAfricanRepublic')`Central African Republic`,
  'TD': t('Subscribe.contries.Chad')`Chad`,
  'CL': t('Subscribe.contries.Chile')`Chile`,
  'CN': t('Subscribe.contries.China')`China`,
  'CX': t('Subscribe.contries.ChristmasIsland')`Christmas Island`,
  'CC': t('Subscribe.contries.CocosKeelingIslands')`Cocos (Keeling) Islands`,
  'CO': t('Subscribe.contries.Colombia')`Colombia`,
  'KM': t('Subscribe.contries.Comoros')`Comoros`,
  'CG': t('Subscribe.contries.Congo')`Congo`,
  'CD': t('Subscribe.contries.CongoTheDemocraticRepublicofthe')`Congo, The Democratic Republic of the`,
  'CK': t('Subscribe.contries.CookIslands')`Cook Islands`,
  'CR': t('Subscribe.contries.CostaRica')`Costa Rica`,
  'CI': t('Subscribe.contries.CoteDIvoire')`Cote D\'Ivoire`,
  'HR': t('Subscribe.contries.Croatia')`Croatia`,
  'CU': t('Subscribe.contries.Cuba')`Cuba`,
  'CY': t('Subscribe.contries.Cyprus')`Cyprus`,
  'CZ': t('Subscribe.contries.CzechRepublic')`Czech Republic`,
  'DK': t('Subscribe.contries.Denmark')`Denmark`,
  'DJ': t('Subscribe.contries.Djibouti')`Djibouti`,
  'DM': t('Subscribe.contries.Dominica')`Dominica`,
  'DO': t('Subscribe.contries.DominicanRepublic')`Dominican Republic`,
  'EC': t('Subscribe.contries.Ecuador')`Ecuador`,
  'EG': t('Subscribe.contries.Egypt')`Egypt`,
  'SV': t('Subscribe.contries.ElSalvador')`El Salvador`,
  'GQ': t('Subscribe.contries.EquatorialGuinea')`Equatorial Guinea`,
  'ER': t('Subscribe.contries.Eritrea')`Eritrea`,
  'EE': t('Subscribe.contries.Estonia')`Estonia`,
  'ET': t('Subscribe.contries.Ethiopia')`Ethiopia`,
  'FK': t('Subscribe.contries.FalklandIslandsMalvinas')`Falkland Islands (Malvinas)`,
  'FO': t('Subscribe.contries.FaroeIslands')`Faroe Islands`,
  'FJ': t('Subscribe.contries.Fiji')`Fiji`,
  'FI': t('Subscribe.contries.Finland')`Finland`,
  'FR': t('Subscribe.contries.France')`France`,
  'GF': t('Subscribe.contries.FrenchGuiana')`French Guiana`,
  'PF': t('Subscribe.contries.FrenchPolynesia')`French Polynesia`,
  'TF': t('Subscribe.contries.FrenchSouthernTerritories')`French Southern Territories`,
  'GA': t('Subscribe.contries.Gabon')`Gabon`,
  'GM': t('Subscribe.contries.Gambia')`Gambia`,
  'GE': t('Subscribe.contries.Georgia')`Georgia`,
  'DE': t('Subscribe.contries.Germany')`Germany`,
  'GH': t('Subscribe.contries.Ghana')`Ghana`,
  'GI': t('Subscribe.contries.Gibraltar')`Gibraltar`,
  'GR': t('Subscribe.contries.Greece')`Greece`,
  'GL': t('Subscribe.contries.Greenland')`Greenland`,
  'GD': t('Subscribe.contries.Grenada')`Grenada`,
  'GP': t('Subscribe.contries.Guadeloupe')`Guadeloupe`,
  'GU': t('Subscribe.contries.Guam')`Guam`,
  'GT': t('Subscribe.contries.Guatemala')`Guatemala`,
  'GG': t('Subscribe.contries.Guernsey')`Guernsey`,
  'GN': t('Subscribe.contries.Guinea')`Guinea`,
  'GW': t('Subscribe.contries.GuineaBissau')`Guinea-Bissau`,
  'GY': t('Subscribe.contries.Guyana')`Guyana`,
  'HT': t('Subscribe.contries.Haiti')`Haiti`,
  'HM': t('Subscribe.contries.HeardIslandAndMcdonaldIslands')`Heard Island and Mcdonald Islands`,
  'VA': t('Subscribe.contries.HolySeeVaticanCityState')`Holy See (Vatican City State)`,
  'HN': t('Subscribe.contries.Honduras')`Honduras`,
  'HK': t('Subscribe.contries.HongKong')`Hong Kong`,
  'HU': t('Subscribe.contries.Hungary')`Hungary`,
  'IS': t('Subscribe.contries.Iceland')`Iceland`,
  'IN': t('Subscribe.contries.India')`India`,
  'ID': t('Subscribe.contries.Indonesia')`Indonesia`,
  'IR': t('Subscribe.contries.IranIslamicRepublicOf')`Iran, Islamic Republic Of`,
  'IQ': t('Subscribe.contries.Iraq')`Iraq`,
  'IE': t('Subscribe.contries.Ireland')`Ireland`,
  'IM': t('Subscribe.contries.IsleOfMan')`Isle of Man`,
  'IL': t('Subscribe.contries.Israel')`Israel`,
  'IT': t('Subscribe.contries.Italy')`Italy`,
  'JM': t('Subscribe.contries.Jamaica')`Jamaica`,
  'JP': t('Subscribe.contries.Japan')`Japan`,
  'JE': t('Subscribe.contries.Jersey')`Jersey`,
  'JO': t('Subscribe.contries.Jordan')`Jordan`,
  'KZ': t('Subscribe.contries.Kazakhstan')`Kazakhstan`,
  'KE': t('Subscribe.contries.Kenya')`Kenya`,
  'KI': t('Subscribe.contries.Kiribati')`Kiribati`,
  'KP': t('Subscribe.contries.KoreaDemocraticPeoplesRepublicof')`Korea, Democratic People\'S Republic of`,
  'KR': t('Subscribe.contries.KoreaRepublicof')`Korea, Republic of`,
  'KW': t('Subscribe.contries.Kuwait')`Kuwait`,
  'KG': t('Subscribe.contries.Kyrgyzstan')`Kyrgyzstan`,
  'LA': t('Subscribe.contries.LaoPeoplesDemocraticRepublic')`Lao People\'S Democratic Republic`,
  'LV': t('Subscribe.contries.Latvia')`Latvia`,
  'LB': t('Subscribe.contries.Lebanon')`Lebanon`,
  'LS': t('Subscribe.contries.Lesotho')`Lesotho`,
  'LR': t('Subscribe.contries.Liberia')`Liberia`,
  'LY': t('Subscribe.contries.LibyanArabJamahiriya')`Libyan Arab Jamahiriya`,
  'LI': t('Subscribe.contries.Liechtenstein')`Liechtenstein`,
  'LT': t('Subscribe.contries.Lithuania')`Lithuania`,
  'LU': t('Subscribe.contries.Luxembourg')`Luxembourg`,
  'MO': t('Subscribe.contries.Macao')`Macao`,
  'MK': t('Subscribe.contries.MacedoniaTheFormerYugoslavRepublicOf')`Macedonia, The Former Yugoslav Republic of`,
  'MG': t('Subscribe.contries.Madagascar')`Madagascar`,
  'MW': t('Subscribe.contries.Malawi')`Malawi`,
  'MY': t('Subscribe.contries.Malaysia')`Malaysia`,
  'MV': t('Subscribe.contries.Maldives')`Maldives`,
  'ML': t('Subscribe.contries.Mali')`Mali`,
  'MT': t('Subscribe.contries.Malta')`Malta`,
  'MH': t('Subscribe.contries.MarshallIslands')`Marshall Islands`,
  'MQ': t('Subscribe.contries.Martinique')`Martinique`,
  'MR': t('Subscribe.contries.Mauritania')`Mauritania`,
  'MU': t('Subscribe.contries.Mauritius')`Mauritius`,
  'YT': t('Subscribe.contries.Mayotte')`Mayotte`,
  'MX': t('Subscribe.contries.Mexico')`Mexico`,
  'FM': t('Subscribe.contries.MicronesiaFederatedStatesOf')`Micronesia, Federated States of`,
  'MD': t('Subscribe.contries.MoldovaRepublicOf')`Moldova, Republic of`,
  'MC': t('Subscribe.contries.Monaco')`Monaco`,
  'MN': t('Subscribe.contries.Mongolia')`Mongolia`,
  'MS': t('Subscribe.contries.Montserrat')`Montserrat`,
  'MA': t('Subscribe.contries.Morocco')`Morocco`,
  'MZ': t('Subscribe.contries.Mozambique')`Mozambique`,
  'MM': t('Subscribe.contries.Myanmar')`Myanmar`,
  'NA': t('Subscribe.contries.Namibia')`Namibia`,
  'NR': t('Subscribe.contries.Nauru')`Nauru`,
  'NP': t('Subscribe.contries.Nepal')`Nepal`,
  'NL': t('Subscribe.contries.Netherlands')`Netherlands`,
  'AN': t('Subscribe.contries.NetherlandsAntilles')`Netherlands Antilles`,
  'NC': t('Subscribe.contries.NewCaledonia')`New Caledonia`,
  'NZ': t('Subscribe.contries.NewZealand')`New Zealand`,
  'NI': t('Subscribe.contries.Nicaragua')`Nicaragua`,
  'NE': t('Subscribe.contries.Niger')`Niger`,
  'NG': t('Subscribe.contries.Nigeria')`Nigeria`,
  'NU': t('Subscribe.contries.Niue')`Niue`,
  'NF': t('Subscribe.contries.NorfolkIsland')`Norfolk Island`,
  'MP': t('Subscribe.contries.NorthernMarianaIslands')`Northern Mariana Islands`,
  'NO': t('Subscribe.contries.Norway')`Norway`,
  'OM': t('Subscribe.contries.Oman')`Oman`,
  'PK': t('Subscribe.contries.Pakistan')`Pakistan`,
  'PW': t('Subscribe.contries.Palau')`Palau`,
  'PS': t('Subscribe.contries.PalestinianTerritoryOccupied')`Palestinian Territory, Occupied`,
  'PA': t('Subscribe.contries.Panama')`Panama`,
  'PG': t('Subscribe.contries.PapuaNewGuinea')`Papua New Guinea`,
  'PY': t('Subscribe.contries.Paraguay')`Paraguay`,
  'PE': t('Subscribe.contries.Peru')`Peru`,
  'PH': t('Subscribe.contries.Philippines')`Philippines`,
  'PN': t('Subscribe.contries.Pitcairn')`Pitcairn`,
  'PL': t('Subscribe.contries.Poland')`Poland`,
  'PT': t('Subscribe.contries.Portugal')`Portugal`,
  'PR': t('Subscribe.contries.PuertoRico')`Puerto Rico`,
  'QA': t('Subscribe.contries.Qatar')`Qatar`,
  'RE': t('Subscribe.contries.Reunion')`Reunion`,
  'RO': t('Subscribe.contries.Romania')`Romania`,
  'RU': t('Subscribe.contries.RussianFederation')`Russian Federation`,
  'RW': t('Subscribe.contries.RWANDA')`RWANDA`,
  'SH': t('Subscribe.contries.SaintHelena')`Saint Helena`,
  'KN': t('Subscribe.contries.SaintKittsAndNevis')`Saint Kitts and Nevis`,
  'LC': t('Subscribe.contries.SaintLucia')`Saint Lucia`,
  'PM': t('Subscribe.contries.SaintPierreAndMiquelon')`Saint Pierre and Miquelon`,
  'VC': t('Subscribe.contries.SaintVincentAndTheGrenadines')`Saint Vincent and the Grenadines`,
  'WS': t('Subscribe.contries.Samoa')`Samoa`,
  'SM': t('Subscribe.contries.SanMarino')`San Marino`,
  'ST': t('Subscribe.contries.SaoTomeAndPrincipe')`Sao Tome and Principe`,
  'SA': t('Subscribe.contries.SaudiArabia')`Saudi Arabia`,
  'SN': t('Subscribe.contries.Senegal')`Senegal`,
  'CS': t('Subscribe.contries.SerbiaAndMontenegro')`Serbia and Montenegro`,
  'SC': t('Subscribe.contries.Seychelles')`Seychelles`,
  'SL': t('Subscribe.contries.SierraLeone')`Sierra Leone`,
  'SG': t('Subscribe.contries.Singapore')`Singapore`,
  'SK': t('Subscribe.contries.Slovakia')`Slovakia`,
  'SI': t('Subscribe.contries.Slovenia')`Slovenia`,
  'SB': t('Subscribe.contries.SolomonIslands')`Solomon Islands`,
  'SO': t('Subscribe.contries.Somalia')`Somalia`,
  'ZA': t('Subscribe.contries.SouthAfrica')`South Africa`,
  'GS': t('Subscribe.contries.SouthGeorgiaAndTheSouthSandwichIslands')`South Georgia and the South Sandwich Islands`,
  'ES': t('Subscribe.contries.Spain')`Spain`,
  'LK': t('Subscribe.contries.SriLanka')`Sri Lanka`,
  'SD': t('Subscribe.contries.Sudan')`Sudan`,
  'SR': t('Subscribe.contries.Suriname')`Suriname`,
  'SJ': t('Subscribe.contries.SvalbardAndJanMayen')`Svalbard and Jan Mayen`,
  'SZ': t('Subscribe.contries.Swaziland')`Swaziland`,
  'SE': t('Subscribe.contries.Sweden')`Sweden`,
  'CH': t('Subscribe.contries.Switzerland')`Switzerland`,
  'SY': t('Subscribe.contries.SyrianArabRepublic')`Syrian Arab Republic`,
  'TW': t('Subscribe.contries.TaiwanProvinceOfChina')`Taiwan, Province of China`,
  'TJ': t('Subscribe.contries.Tajikistan')`Tajikistan`,
  'TZ': t('Subscribe.contries.TanzaniaUnitedRepublicOf')`Tanzania, United Republic of`,
  'TH': t('Subscribe.contries.Thailand')`Thailand`,
  'TL': t('Subscribe.contries.TimorLeste')`Timor-Leste`,
  'TG': t('Subscribe.contries.Togo')`Togo`,
  'TK': t('Subscribe.contries.Tokelau')`Tokelau`,
  'TO': t('Subscribe.contries.Tonga')`Tonga`,
  'TT': t('Subscribe.contries.TrinidadAndTobago')`Trinidad and Tobago`,
  'TN': t('Subscribe.contries.Tunisia')`Tunisia`,
  'TR': t('Subscribe.contries.Turkey')`Turkey`,
  'TM': t('Subscribe.contries.Turkmenistan')`Turkmenistan`,
  'TC': t('Subscribe.contries.TurksAndCaicosIslands')`Turks and Caicos Islands`,
  'TV': t('Subscribe.contries.Tuvalu')`Tuvalu`,
  'UG': t('Subscribe.contries.Uganda')`Uganda`,
  'UA': t('Subscribe.contries.Ukraine')`Ukraine`,
  'AE': t('Subscribe.contries.UnitedArabEmirates')`United Arab Emirates`,
  'GB': t('Subscribe.contries.UnitedKingdom')`United Kingdom`,
  'US': t('Subscribe.contries.UnitedStates')`United States`,
  'UM': t('Subscribe.contries.UnitedStatesMinorOutlyingIslands')`United States Minor Outlying Islands`,
  'UY': t('Subscribe.contries.Uruguay')`Uruguay`,
  'UZ': t('Subscribe.contries.Uzbekistan')`Uzbekistan`,
  'VU': t('Subscribe.contries.Vanuatu')`Vanuatu`,
  'VE': t('Subscribe.contries.Venezuela')`Venezuela`,
  'VN': t('Subscribe.contries.VietNam')`Viet Nam`,
  'VG': t('Subscribe.contries.VirginIslandsBritish')`Virgin Islands, British`,
  'VI': t('Subscribe.contries.VirginIslandsUS')`Virgin Islands, U.S.`,
  'WF': t('Subscribe.contries.WallisAndFutuna')`Wallis and Futuna`,
  'EH': t('Subscribe.contries.WesternSahara')`Western Sahara`,
  'YE': t('Subscribe.contries.Yemen')`Yemen`,
  'ZM': t('Subscribe.contries.Zambia')`Zambia`,
  'ZW': t('Subscribe.contries.Zimbabwe')`Zimbabwe`,
}
