export const planet = () => import('./animations/planet.json')
export const tranparency = () => import('./animations/tranparency.json')
export const radar = () => import('./animations/radar.json')
export const hourglass = () => import('./animations/hourglass.json')
export const error = () => import('./animations/error.json')
